import {
  Amphora,
  Bike,
  BookOpen,
  CirclePlay,
  CookingPot,
  Dumbbell,
  Footprints,
  HandFist,
  Headphones,
  Heart,
  Languages,
  MountainSnow,
  Music,
  NotebookPen,
  Origami,
  Palette,
  Pencil,
  Rose,
  ScissorsLineDashed,
  Sparkles,
  Spool,
  SunMedium,
  Volleyball,
  Waves,
} from 'lucide-vue-next'

const activityIconMap = {
  amphora: Amphora,
  bike: Bike,
  book: BookOpen,
  'circle-play': CirclePlay,
  'cooking-pot': CookingPot,
  dumbbell: Dumbbell,
  footprints: Footprints,
  'hand-fist': HandFist,
  headphones: Headphones,
  heart: Heart,
  languages: Languages,
  'mountain-snow': MountainSnow,
  music: Music,
  'notebook-pen': NotebookPen,
  origami: Origami,
  palette: Palette,
  pencil: Pencil,
  rose: Rose,
  'scissors-line-dashed': ScissorsLineDashed,
  spool: Spool,
  'sun-medium': SunMedium,
  volleyball: Volleyball,
  waves: Waves,
}

export function iconFor(iconName) {
  return activityIconMap[iconName] || Sparkles
}
